matrix:
  include:
    language: java
      jdk: oraclejdk8

    language: python
      python: 3.7.2

    exclude: *.pdf

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

deploy:
  skip_cleanup: true